server:
  port: 80
####服务网关名称
spring:
  application:
    name: mayikt-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          ###允许通过注册中心获取地址调用
          enabled: true
      ###路由策略
      routes:
        ###根据我们的服务名称查找地址实现调用
        - id: member
          ####转发http://www.mayikt.com/
          uri: lb://meitemayikt-order/
          filters:
            - StripPrefix=1
          ###匹配规则
          predicates:
            - Path=/orderFeignToMember/**